[build]
  command = "pnpm --dir product/frontend build"
  publish = "product/frontend/.next"

[build.environment]
  NODE_VERSION = "20"
  PNPM_VERSION = "8.15.1"
  NEXT_DISABLE_NETLIFY_EDGE = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "./netlify-plugin-fix-next-runtime"
