[build]
  base = "product/frontend"
  command = "pnpm build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  PNPM_VERSION = "8.15.1"
  NEXT_DISABLE_NETLIFY_EDGE = "true"
  SECRETS_SCAN_OMIT_PATHS = ".netlify/**,.next/**"
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_CLERK_SIGN_UP_URL,NEXT_PUBLIC_CLERK_FALLBACK_URL,NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME"

[[plugins]]
  package = "@netlify/plugin-nextjs"