import localFont from "next/font/local";
import Navbar from "../components/navbar/Navbar";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";

config.autoAddCss = false;

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "KUMA- Social App",
  description: "Generated by Dana Khaing",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <header className="fixed top-0 left-0 w-full z-50">
            <Navbar />
          </header>
          <main className="mt-20">{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
